import { SHADOWS_LIGHT, type ThemePresetMeta, type ThemeTokenMap } from "./types.js";

/** Product marketing landing — NYC Night (night-gold). Catalog-only; not a storefront seed. */
export const marketingTokensMap: ThemeTokenMap = {
  background: "#07080d",
  foreground: "#f5f3ef",
  card: "#10131c",
  cardForeground: "#f5f3ef",
  popover: "#10131c",
  popoverForeground: "#f5f3ef",
  primary: "#c9a227",
  primaryForeground: "#07080d",
  secondary: "#161a26",
  secondaryForeground: "#f5f3ef",
  muted: "#161a26",
  mutedForeground: "#9ca3af",
  accent: "#d4af37",
  accentForeground: "#07080d",
  destructive: "#b91c1c",
  border: "#252a3a",
  input: "#252a3a",
  ring: "#c9a227",
  chart1: "#c9a227",
  chart2: "#d4af37",
  chart3: "#8a7020",
  chart4: "#9ca3af",
  chart5: "#6b7280",
  sidebar: "#0b0d14",
  sidebarForeground: "#f5f3ef",
  sidebarPrimary: "#c9a227",
  sidebarPrimaryForeground: "#07080d",
  sidebarAccent: "#161a26",
  sidebarAccentForeground: "#f5f3ef",
  sidebarBorder: "#252a3a",
  sidebarRing: "#c9a227",
  radius: "8px",
  fontSans: '"Inter", "Segoe UI", system-ui, sans-serif',
  fontDisplay: '"Plus Jakarta Sans", "Inter", system-ui, sans-serif',
  flashBg: "color-mix(in srgb, #c9a227 16%, #10131c)",
  flashBorder: "color-mix(in srgb, #c9a227 35%, #252a3a)",
  ...SHADOWS_LIGHT,
  colorScheme: "dark",
};

export const marketingPreset: ThemePresetMeta = {
  id: "marketing",
  label: "Marketing NYC Night",
  catalogOnly: true,
  tokens: marketingTokensMap,
};
