import { SHADOWS_LIGHT, type ThemePresetMeta, type ThemeTokenMap } from "./types.js";

/** Admin console — Obsidian Soft (graphite + soft lilac accent). */
export const platformTokensMap: ThemeTokenMap = {
  background: "#19191c",
  foreground: "#e6e6ea",
  card: "#232328",
  cardForeground: "#e6e6ea",
  popover: "#232328",
  popoverForeground: "#e6e6ea",
  primary: "#a78bfa",
  primaryForeground: "#120f1c",
  secondary: "#2c2c33",
  secondaryForeground: "#e6e6ea",
  muted: "#2c2c33",
  mutedForeground: "#9a9aa3",
  accent: "#2c2c33",
  accentForeground: "#e6e6ea",
  destructive: "#e06c75",
  border: "#34343d",
  input: "#34343d",
  ring: "#a78bfa",
  chart1: "#a78bfa",
  chart2: "#9a9aa3",
  chart3: "#2c2c33",
  chart4: "#3f3f4a",
  chart5: "#e6e6ea",
  sidebar: "#131316",
  sidebarForeground: "#e6e6ea",
  sidebarPrimary: "#a78bfa",
  sidebarPrimaryForeground: "#120f1c",
  sidebarAccent: "#2c2c33",
  sidebarAccentForeground: "#e6e6ea",
  sidebarBorder: "#2c2c33",
  sidebarRing: "#c4b5fd",
  radius: "8px",
  fontSans: '"Inter", "Segoe UI", system-ui, sans-serif',
  fontDisplay: '"Plus Jakarta Sans", "Inter", system-ui, sans-serif',
  flashBg: "color-mix(in srgb, #a78bfa 16%, #232328)",
  flashBorder: "color-mix(in srgb, #a78bfa 35%, #34343d)",
  ...SHADOWS_LIGHT,
  colorScheme: "dark",
};

export const platformPreset: ThemePresetMeta = {
  id: "platform",
  label: "Platform admin",
  catalogOnly: true,
  tokens: platformTokensMap,
};
