import { SHADOWS_LIGHT, type ThemePresetMeta, type ThemeTokenMap } from "./types.js";

/** Admin console — Mestryx Teal (CV color logic; Inter + Plus Jakarta unchanged). */
export const platformTokensMap: ThemeTokenMap = {
  background: "#0b0f14",
  foreground: "#e2e8f0",
  card: "#0f172a",
  cardForeground: "#e2e8f0",
  popover: "#0f172a",
  popoverForeground: "#e2e8f0",
  primary: "#5eead4",
  primaryForeground: "#0b0f14",
  secondary: "#1e293b",
  secondaryForeground: "#e2e8f0",
  muted: "#1e293b",
  mutedForeground: "#94a3b8",
  accent: "#1e293b",
  accentForeground: "#e2e8f0",
  destructive: "#e06c75",
  border: "#334155",
  input: "#334155",
  ring: "#5eead4",
  chart1: "#5eead4",
  chart2: "#94a3b8",
  chart3: "#1e293b",
  chart4: "#334155",
  chart5: "#e2e8f0",
  sidebar: "#0f172a",
  sidebarForeground: "#e2e8f0",
  sidebarPrimary: "#5eead4",
  sidebarPrimaryForeground: "#0b0f14",
  sidebarAccent: "#1e293b",
  sidebarAccentForeground: "#e2e8f0",
  sidebarBorder: "#1e293b",
  sidebarRing: "#99f6e4",
  radius: "8px",
  fontSans: '"Inter", "Segoe UI", system-ui, sans-serif',
  fontDisplay: '"Plus Jakarta Sans", "Inter", system-ui, sans-serif',
  flashBg: "color-mix(in srgb, #5eead4 16%, #0f172a)",
  flashBorder: "color-mix(in srgb, #5eead4 35%, #334155)",
  ...SHADOWS_LIGHT,
  colorScheme: "dark",
};

export const platformPreset: ThemePresetMeta = {
  id: "platform",
  label: "Platform admin",
  catalogOnly: true,
  tokens: platformTokensMap,
};
